Repository persian-tools/persian-tools, pull requests merged in 2021-03, with the labels that each got.

#48 fix:clean up addOrdinaSuffix and add error handling
  src/modules/addOrdinalSuffix/addOrdinalSuffix.ts
  test/addOrdinalSuffix.spec.ts
Labels: documentation, enhancement

#47 Add number plate module
  README.md
  src/index.ts
  src/modules/numberplate/codes.skip.ts
  src/modules/numberplate/helpers.ts
  src/modules/numberplate/index.ts
  src/modules/numberplate/types.skip.ts
  test/numberplate.spec.ts
Labels: New feature, Under Review

#55 feat(digitsEnToFa): add error handling and clean up
  src/modules/digits/index.ts
  test/digits.spec.ts
Labels: New feature, Under Review, enhancement

#61 remove commas from decimal places in addCommas module
  src/modules/commas/add.ts
  test/addCommas.spec.ts
Labels: bug, documentation
